### ISSUE TITLE
How to pass parameters to push and run Docker images

### ISSUE THREAD

**Issue by nabiltntn** [cloudfoundry/docs-cf-admin#101]
Hi,

I can't see in documentation how it's possible to pass parameters to run Dockee image like `-p` or 
 `-e`.

Is it possible to use them ?

**Comment by dkoper** [comment]
Hi @nabiltntn 

I assume you are referring to pushing a Docker app and want to set environment variables for the app?
You can either push the app with an app manifest file that [declares the environment variables](http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#env-block), or push your Docker app first (with `cf push APP -o IMAGE`) followed by `cf set-env` for each environment variable you want to set.

**Comment by weibeld** [comment]
@dkoper if I run

```
cf push APP -o IMAGE
cf set-env VAR value
```

can't it be that the Docker image is already started without the variable `VAR`?

Is it necessary to run `cf restage APP` after `cf set-env`, like this?

``` 
cf push APP -o IMAGE
cf set-env VAR value
cf restage APP
```

**Comment by cheahkhing** [comment]
Hi, any reason this is closed? is this supported?

I am looking for ways to push and run docker images with parameters like: -v "xxx:ccc" to mount certain volumes.

Is this doable?

**Comment by loafoe** [comment]
@cheahkhing typically not. Your CF deployment would need to support volume services. See here for details:

https://docs.cloudfoundry.org/devguide/services/using-vol-services.html
