### ISSUE TITLE
cf create-user doesn't reference "--origin" 

### ISSUE THREAD

**Issue by jbpivotal** [cloudfoundry/docs-cf-admin#107]
On this cf create-user docs page... https://docs.cloudfoundry.org/adminguide/cli-user-management.html#create-user
...there's no reference to the --origin option that is included in the cf cli help listed below.

The use case is that admins may have multiple origins, and this option can enable them to specify the correct one. You may want to contact UAA for more details.

---
cf cli help:

$ cf create-user -h
NAME:
   create-user - Create a new user

USAGE:
   cf create-user USERNAME PASSWORD
   cf create-user USERNAME --origin ORIGIN

EXAMPLES:
   cf create-user j.smith@example.com S3cr3t                  # internal user
   cf create-user j.smith@example.com --origin ldap           # LDAP user
   cf create-user j.smith@example.com --origin provider-alias # SAML or OpenID Connect federated user

OPTIONS:
   --origin      Origin for mapping a user account to a user in an external identity provider

SEE ALSO:
   passwd, set-org-role, set-space-role

**Comment by animatedmax** [comment]
Hi @jbpivotal We've added the --origin flag to our examples. Thanks!
