### ISSUE TITLE
notifications.html.md.erb needs an example of sending a notification

### ISSUE THREAD

**Issue by cdelashmutt-pivotal** [cloudfoundry/docs-cf-admin#116]
The instructions at https://github.com/cloudfoundry/docs-cf-admin/blob/master/notifications.html.md.erb talk about setting up for sending a notification, but there is no example included for actually sending the notification.  Alternatively, a link to the API for the notifications service might suffice.

**Comment by animatedmax** [comment]
Hi @cdelashmutt-pivotal 
We've added a "Send a Notification" section to the topic with a link to V1_API.md and a usage example. Thanks for the suggestion!
