### ISSUE TITLE
Mutual Authentication with Clients section extremely unclear on the setting to use when terminating at the GoRouter

### ISSUE THREAD

**Issue by matthewfischer** [cloudfoundry/docs-cf-admin#135]
When reading the section - "Mutual Authentication with Clients" (https://docs.pivotal.io/pivotalcf/2-3/adminguide/securing-traffic.html#gorouter_mutual_auth), the correct setting is extremely unclear due to what seems to be contradictory instructions.

First we see this section:

**Router does not request client certificates.** The Gorouter does not request client certificates in TLS handshakes so clients will not provide them and validation of client certificates does not occur. This option is incompatible with the XFCC configuration options **TLS terminated for the first time at HAProxy** and **TLS terminated for the first time at the Router** in PAS because these options require mutual authentication.

This section implies that if you Terminate at the GoRouter you CANNOT use this setting due to the second clause: "This option is incompatible with the XFCC configuration options....  **TLS terminated for the first time at the Router**".  

Then later in the same doc, it says bluntly that **Router does not request client certificates.** is the **ONLY** valid setting to use if terminating the GoRouter:

If Gorouter is the first point of TLS termination (your load balancer does not terminate TLS, and passes the request through to Gorouter over TCP), consider the following:

    Only option Router does not request client certificates should be used with PAS, as the Gorouters are in that product receive requests for the system domain. Many clients of CF platform APIs do not present client certificates in TLS handshakes, so the first point of TLS termination for requests to the system domain must not request them.

My Suspicion is that the clause of **TLS terminated for the first time at the Router** should probably instead be **TLS terminated for the first time at the load balancer**, but I am not 100% sure on that.

**Comment by pspinrad** [comment]
Hey @matthewfischer -- sorry for lateness and thanks for pointing this out.  @shalako can you help, or any pointers?  Thanks!

**Comment by pspinrad** [comment]
@shalako pinging you again on this, "extremely unclear" section in routing docs :-P

**Comment by mlimonczenko** [comment]
Hello @matthewfischer,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
