### ISSUE TITLE
Curl uaac notification url

### ISSUE THREAD

**Issue by lalitprasanth12** [cloudfoundry/docs-cf-admin#146]
uaac curl https://notifications.user.example.com/notifications -X PUT --data '{  "source_name": "Cloud Ops Team",
  "notifications": {
     "system-going-down": {"critical": true, "description": "Cloud going down" },
     "system-up": { "critical": true, "description": "Cloud back up" }
     }
 }'
--------------------
What does the url refer to from the above command? 
When I tried https://notifications.<uaac target endpoint>/notifications , I am getting 404. should I enable something for this to work?

**Comment by mlimonczenko** [comment]
Hello @lalitprasanth12. Can you provide me the file you found this command?
