### ISSUE TITLE
Outside PCF, I have a CAS (sso) server of HTTPS protocol. The client is located on PCF. How should I arrange certificates on PCF?

### ISSUE THREAD

**Issue by niocoders** [cloudfoundry/docs-cf-admin#149]
Outside PCF, I have a CAS (sso) server of HTTPS protocol. The client is located on PCF. How should I arrange certificates on PCF?

**Comment by mlimonczenko** [comment]
Hello @niocoders,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
