### ISSUE TITLE
Unclear statement in securing-traffic.html.md.erb

### ISSUE THREAD

**Issue by jeanmarc** [cloudfoundry/docs-cf-admin#163]
https://github.com/cloudfoundry/docs-cf-admin/blob/12.0/securing-traffic.html.md.erb

line 321 "If the Gorouter is the first point of TLS,"

What is meant here? If it is the first TLS termination point (i.e. the load balancer uses 'pass through' mode)? 

Perhaps rephrasing to "When terminating TLS at the Gorouter only," is more clear?

**Comment by mlimonczenko** [comment]
Thank you very much, @jeanmarc. We have determined the way you chose to rephrase is accurate. We have incorporated the change.
