### ISSUE TITLE
Is External Domain configurable?

### ISSUE THREAD

**Issue by agregory999** [cloudfoundry/docs-cf-admin#170]
We see that the doc here talks about configuring External Domain:
https://docs.pivotal.io/platform/application-service/2-8/operating/deploying-service-mesh.html

This page says it is a limitation that it is hardcoded to *.mesh.apps-domain.com

Can we make the docs consistent?

**Comment by paigecalvert** [comment]
Thanks @agregory999! To confirm: is the only change here to add an `*` to the beginning of `.mesh.apps-domain.com`?

**Comment by mlimonczenko** [comment]
Hello @agregory999,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
