### ISSUE TITLE
buildpack locked

### ISSUE THREAD

**Issue by avasseur-pivotal** [cloudfoundry/docs-cf-admin#47]
I find the doc on buildpack lock too short
https://github.com/cloudfoundry/docs-cf-admin/blob/master/buildpacks.html.md.erb

Scenario is that
- cf ops install a cf-release version X with buildpack (say Java BP) 3.6
- cf admin update JBP to 3.8.1 (note JBP 3.6 does not support spring boot 1.4 for example)
- cf admin does not lock the buildpack (default)
any deploy would remove the upgraded buildpack and return to the cf-release defined one
(that will then mean any deployed spring boot 1.4 app will stop working if restage, which means risk of downtime while cf admin and cf ops introduces divergence)

I think we should provide more emphasys on buildpack lock and suggest a best practice after any buildpack upgrade or such.

**Comment by jncd** [comment]
Hi @avasseur-pivotal Thanks for logging this issue. We'll look into it and make fixes to the doc.

**Comment by kdolor-pivotal** [comment]
@avasseur-pivotal Thank you for logging this issue. This has been addressed and the changes are reflected here: https://docs.cloudfoundry.org/adminguide/buildpacks.html#lock
