### ISSUE TITLE
Detail whether quota account for stopped apps

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-cf-admin#48]
Currently, https://github.com/cloudfoundry/docs-cf-admin/blob/master/quota-plans.html.md.erb does not precise whether cloudfoundry enforces memory usage by counting stopped apps, and crashed/starting app instances.

In other words, when reaching a quota limit, can users stop apps to leave room for other apps to start within quotas, or should user instead reduce number of app instances or stop applications.

**Comment by ljarzynski** [comment]
Thanks for filing this issue @gberche-orange. @SocalNick, are you able to clarify and help us ensure the docs are correct?

**Comment by SocalNick** [comment]
Stopped apps do not count against quota. Crashed do because the desired state is running.

**Comment by ljarzynski** [comment]
Thanks @SocalNick! 

@gberche-orange - I've updated our docs to add this information: https://github.com/cloudfoundry/docs-cf-admin/commit/3dd57a3ba98759882d6e70c3511862d2e224031b.

**Comment by gberche-orange** [comment]
thanks @SocalNick and @ljarzynski for clarifying behavior w.r.t. ``app_instance_limit``

I believe the same precision is also needed for the ``memory_limit`` within an organization. 
https://github.com/cloudfoundry/docs-cf-admin/blob/3dd57a3ba98759882d6e70c3511862d2e224031b/quota-plans.html.md.erb#L27

Sorry my report was precise enough in the 1st place and was not mentioning RAM.
