### ISSUE TITLE
Detail how to control disk size limit in containers

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-cf-admin#49]
The current quota management does not include the app instance ephemeral disk storage limit.

The cf app command however still display the upper disk quota (returned by the http://apidocs.cloudfoundry.org/247/apps/get_detailed_stats_for_a_started_app.html CC API)

``
cf app hello-world
Showing health and status for app hello-world in [...]
OK

requested state: started
instances: 1/1
usage: 512M x 1 instances
[...]

     state     since                    cpu    memory         disk         details
#0   running   2016-11-23 10:13:59 AM   0.0%   3.6M of 512M   6.8M of 1G
`` 

It would be useful to mention in https://github.com/cloudfoundry/docs-cf-admin/blob/master/quota-plans.html.md.erb that the 1G disk limit is configurable per CF deployment within the http://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/cf-release&version=247#p=cc.default_app_disk_in_mb property.

**Comment by ljarzynski** [comment]
Thanks @gberche-orange. @SocalNick do you agree? If so, I can go ahead and update the docs accordingly.

**Comment by SocalNick** [comment]
The `cf app` command doesn't display the upper disk quota of the deployment, it displays the app disk quota. The app disk quota should not be documented on the [Creating and Modifying Quota Plans](https://docs.cloudfoundry.org/adminguide/quota-plans.html) as it's not governed by quotas.

Application disk quotas can be set to anything between 0 and the deployment [maximum_app_disk_in_mb](http://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/cf-release&version=247#p=cc.maximum_app_disk_in_mb). This is done with the CLI `cf push -k` flag, which is shown by `cf push -h` and shown here: http://cli.cloudfoundry.org/en-US/cf/push.html

**Comment by ljarzynski** [comment]
Thanks for the explanation @SocalNick!

**Comment by gberche-orange** [comment]
@SocalNick thanks for the useful clarification. 

I would have feel it would make sense to add a "Note: " within this page clarifying max disk isn't controllable by current quotas, and rather at the deployment level through the [maximum_app_disk_in_mb](http://bosh.io/jobs/cloud_controller_ng?source=github.com/cloudfoundry/cf-release&version=247#p=cc.maximum_app_disk_in_mb) cloudcontroller property ).

@ljarzynski  
If not where would this information be documented instead if the  [Creating and Modifying Quota Plans](https://docs.cloudfoundry.org/adminguide/quota-plans.html) is not the right place ?
