### ISSUE TITLE
UAA Admin user required to manage roles??

### ISSUE THREAD

**Issue by dkoper** [cloudfoundry/docs-cf-admin#52]
I find the line [To manage users, organizations, and roles with the cf CLI, you must log in with <strong>UAA Administrator user credentials</strong>.](https://github.com/cloudfoundry/docs-cf-admin/blob/master/cli-user-management.html.md.erb#L15) confusing/misleading, and just received a feature request for the cf CLI to do make role management possible by Org Managers. It already is!

I'm not sure what "UAA Administrator user credentials" means - did a search and this is the only page that uses "UAA Administrator". Is that different from the CF operator (the "admin")?

Assuming it is the same, note that if the feature flag `set_roles_by_username` is enabled, Org Managers can assign roles to (existing) users in their org. Even Space Managers can assign (space) roles to users in their space.

**Comment by bentarnoff** [comment]
Hey @dkoper thanks for this! To clarify, "UAA Administrator user credentials" in this context means that you must obtain the credentials from navigating to the Elastic Runtime tile, clicking the **Credentials** tab, scrolling down to the **UAA** section, and clicking **Link to Credential** next to **Admin Credentials**. We can refer to these as the "admin" or "operator" credentials if that's more accurate, and we can also include a more complete explanation of how to find them.

We will also document the feature flag `set_roles_by_username`. Can you give us an example of how to set that flag on the command line?

Thanks!

**Comment by dkoper** [comment]
@bentarnoff `tile`? I was referring to the OSS documentation.

I think feature flags are documented already somewhere?
```
host@cloud-cf:~/workspace$ ./cf enable-feature-flag set_roles_by_username
Setting status of set_roles_by_username as admin...

OK

Feature set_roles_by_username Enabled.
```

**Comment by bentarnoff** [comment]
Sorry about that @dkoper! And thanks for the info about feature flags. We'll update this topic.

**Comment by bentarnoff** [comment]
Hey @dkoper please take a look at the revised topic on our staging site and let us know if you have any feedback: https://docs-cloudfoundry-staging.cfapps.io/adminguide/cli-user-management.html

**Comment by dkoper** [comment]
@bentarnoff Looks good!

**Comment by bentarnoff** [comment]
Great, thanks!
