### ISSUE TITLE
Behavior about the default Isolation Segment differs from expected

### ISSUE THREAD

**Issue by nota-ja** [cloudfoundry/docs-cf-admin#60]
The document
https://docs.cloudfoundry.org/adminguide/isolation-segments.html#add_org_is
says that

> When you add an org to one isolation segment, it becomes the default isolation segment for that org unless another default is already set. This means that new spaces created within the org will be in its default isolation segment unless specified otherwise.

(source code: https://github.com/cloudfoundry/docs-cf-admin/blob/78c9ad215bc7d6fe1e8136754b8a7342e05a4729/isolation-segments.html.md.erb#L271)

However, when I added an org to an isolation segment that is not `shared`, it did not become the default isolation segment for the org.

I've checked the source code of Cloud Controller NG and found that the current implementation seems (intentionally) to not set the default isolation segment on adding orgs if the IS is not `shared` segment.
https://github.com/cloudfoundry/cloud_controller_ng/blob/70f794ca6e2aa9d718fabe3d1e84f4fe5dcc5a29/app/actions/isolation_segment_assign.rb#L11-L15
```ruby
          if org.default_isolation_segment_model.nil?
            if isolation_segment.is_shared_segment?
              org.update(default_isolation_segment_model: isolation_segment)
            end
          end
```

The unit tests for the method seem backing this intention.
* https://github.com/cloudfoundry/cloud_controller_ng/blob/70f794ca6e2aa9d718fabe3d1e84f4fe5dcc5a29/spec/unit/actions/isolation_segment_assign_spec.rb#L30-L33
* https://github.com/cloudfoundry/cloud_controller_ng/blob/70f794ca6e2aa9d718fabe3d1e84f4fe5dcc5a29/spec/unit/actions/isolation_segment_assign_spec.rb#L66-L71

What's your thought on this?

**Comment by ljarzynski** [comment]
Thanks for raising this issue as well, @nota-ja! @SocalNick Would appreciate your help on parsing this and identifying how we should update the doc.

**Comment by SocalNick** [comment]
cc @zrob (new CAPI PM)

**Comment by ljarzynski** [comment]
Hey @zrob! Just wanted to follow up on this and see what your thoughts were

**Comment by zrob** [comment]
I believe this was fixed here: https://github.com/cloudfoundry/docs-cf-admin/pull/64

**Comment by ljarzynski** [comment]
@zrob You're right, thanks! @nota-ja Please see the changes merged in the link provided above.
