### ISSUE TITLE
Insufficient scope error

### ISSUE THREAD

**Issue by johnyesberg** [cloudfoundry/docs-cf-admin#73]
Inspired by the simple example at https://docs.cloudfoundry.org/adminguide/cli-user-management.html
I tried this:

  > cf create-user john pswd
  Creating user john...
  FAILED
  Error creating user john.
  Server error, status code: 403, error code: insufficient_scope, message: Insufficient scope for this resource

I don't understand the error message. I'll have to search.

**Comment by ljarzynski** [comment]
Hi @johnyesberg. Are you logged into the cf CLI as an admin user? It seems like you do not have the permissions to create users.

**Comment by johnyesberg** [comment]
Thanks @ljarzynski . I had enough privilege to create the uaa. But I suspect as you say I don't have sufficient permission to create users. If I understood the permissions/scopes model better, I'd be tempted to make a pull request on that guide to add an "Errors you may encounter" section. Can you recommend a reference for me?

**Comment by ljarzynski** [comment]
@johnyesberg Do these help?

- http://docs.cloudfoundry.org/concepts/roles.html
- http://docs.cloudfoundry.org/adminguide/uaa-user-management.html

**Comment by bentarnoff** [comment]
Hi @johnyesberg I'm closing this issue but please feel free to reach out if you have any further feedback.
