### ISSUE TITLE
For non-OSS the "Prepare BOSH to Support Isolation Segments" subtopic shows up incorrectly

### ISSUE THREAD

**Issue by chrisumbel** [cloudfoundry/docs-cf-admin#82]
The intention of the code seems to be that only OSS CF should have the "Prepare BOSH to Support Isolation Segments" subtopic because of:

```
<% if vars.product_name == 'CF' %>
## <a id="prepare"></a>Prepare BOSH to Support Isolation Segments

To enable isolation segments for a deployment, you must first assign Diego cells a `placement_tags` property in your Diego manifest by following the steps below:
```
But the "Prepare BOSH to Support Isolation Segments" subtopic heading shows up in the ToC in the PCF docs as well, but the link is dead presumably because the "<a id="prepare"></a>" is never rendered. I guess the ToC is built by scanning the document without regards to what actually ends up getting rendered in the end?

**Comment by animatedmax** [comment]
Hi @chrisumbel This issue has been resolved. Thanks for pointing it out!
