### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by paulc4** [cloudfoundry/docs-cf-admin#88]
In **Pre-Deployment Steps**, Step 3 and Step 5:

- Link to AWS links to unknown page
- Link for OpenStack and vSphere resolves to Step 18, but it _should_ resolve to item 18 of Step 4

**Comment by bentarnoff** [comment]
Thanks for bringing this to our attention, @paulc4. We've updated the "Enabling TCP Routing" topic and the revised version should be live on our site soon. In the future, please indicate the name of the topic you're referring to when creating GitHub issues, because the issue is repo-wide. Thanks.
