### ISSUE TITLE
Allowed role to create buildpack

### ISSUE THREAD

**Issue by amiramw** [cloudfoundry/docs-cf-admin#92]
AFAIK [this note](https://github.com/cloudfoundry/docs-cf-admin/blob/master/buildpacks.html.md.erb#L18) is not accurate. It is not enough to be org admin in order to create a buildpack. You must be cloud controller admin in order to do that.
Am I right?

**Comment by dkoper** [comment]
@amiramw Correct! I see it's been fixed.
