### ISSUE TITLE
Ambiguous! Isn't the container port always 8080 on Diego 

### ISSUE THREAD

**Issue by xtreme-sina** [cloudfoundry/docs-cf-admin#96]
https://github.com/cloudfoundry/docs-cf-admin/blob/a2531626f97b32d8e6a54b6c3f45f4823cd0f23c/docker.html.md.erb#L94

What's the relationship between the lowest port exposed by the Docker image and $PORT (8080 on Diego) set by Cloud Controller?

**Comment by pspinrad** [comment]
8080 is default, overridden by any explicit [EXPOSE](https://docs.docker.com/engine/reference/builder/#expose) definitions in the Dockerfile. If ports are explicitly exposed, then CF traffic routes to lowest-number exposed port, and if not, it routes to 8080.  Changed docs to explain.  Thanks for the great question!
