### ISSUE TITLE
Disk limit on per container

### ISSUE THREAD

**Issue by rjain-pivotal** [cloudfoundry/docs-cf-admin#98]
This is not a doc issue (https://github.com/cloudfoundry/docs-cf-admin/issues/49) but I wuld like to know why do we have a limit on the container image size. Why not constrain it by org/space quota but the size of the container is not restricted at a deployment level. 

Use cases: 

i can have some 2 GB, 1 GB or 4 GB containers. I don't want to have a site wide 4 GB size and 4 GB reserved for every container, rather based on the manifest file I can control the size of the container. 

Thanks, Rajesh

**Comment by animatedmax** [comment]
Hi @rjain-pivotal This is a good question, but I don't think we (tech writers) can give you the complete answer. I highly recommend asking this is a Slack channel, or by sending an email to one of our mailing lists. Thanks!
